export const environment = {
  production: true,
  applicationId : '39488dda8af85a2bb0582f78265b446d49e13ab8e4d047e0a21f9f9bba44079e',
  categorias : [
    'Pantalones',
    'Faldas',
    'Camisas',
    'Camisetas',
    'Complementos',
    'Bolsos',
    'Bañadores',
    'Shorts',
    'Polos',
    'Sudaderas',
    'Básicos'
  ],
  prendas : [
    'Polo print palmeras y calaveras',
    'Camiseta manga corta logo',
    'Camiseta Don\'t Wanna Fight\' camuflaje',
    'Camiseta básica cuello pico',
    'Polo manga corta paneles',
    'Pantalón chino skinny fit',
    'Pantalón jogging rayas laterales',
    'Pantalón chino con cinturón',
    'Bañador liso en varios colores',
    'Bañador corto colores ribete',
    'Bañador estampado de camuflaje',
    'Bañador print Maui and Sons',
    'Bañador estampado con cordón',
    'Bañador slip liso',
    'Shorts denim mom fit',
    'Shorts denim mom fit banda lateral',
    'Shorts deportivos bandas texto',
    'Shorts denim tiro medio',
    'Bermuda tailoring rayas',
    'Shorts denim mom fit',
    'Shorts denim laterales escotados',
    'Chaqueta crochet rayas capucha',
    'Jersey color block en contraste',
    'Jersey de punto perlado'
  ]
};
